### ISSUE TITLE
Issue with Character Size after Shrinking

### ISSUE THREAD

**Issue by LokeYourC3PH** [CammiePone/Resize-Potion#10]
So, I first thought it would be Mo'Bends that causes this issue, and as such I removed the mod from my client, but it still doesn't work. Whenever I shrink myself or change size, my camera/eye height changes and I can move between blocks, so my hitbox is changed, but my character model stays the same size as it always does, and I am not sure how I can fix this. Please advise.

Pics (Shrink 2 was applied to myself):
![2019-03-29_16 55 17](https://user-images.githubusercontent.com/5807595/55245462-7e7e3e80-5243-11e9-9c68-9fbe3eccb104.png)
![2019-03-29_16 55 22](https://user-images.githubusercontent.com/5807595/55245471-8211c580-5243-11e9-9c46-5077bd90dd0a.png)

**Comment by CammiePone** [comment]
Can I ask for a list of mods?

**Comment by LokeYourC3PH** [comment]
Oh of course, my mistake: 

![image](https://user-images.githubusercontent.com/5807595/55245969-88547180-5244-11e9-982a-dac96c9dec08.png)
![image](https://user-images.githubusercontent.com/5807595/55246005-973b2400-5244-11e9-888c-edb0e8dee871.png)

If you need anything else just tell me :D

**Comment by CammiePone** [comment]
Okay, here's my ideas: Cyberware, Mob Dismemberment, or Obfuscate. Those all mess with player models, so it's possible that one of them replaces the player model with a custom one.

**Comment by LokeYourC3PH** [comment]
Hmm very likely (I hope not) Cyberware, will try without.

**Comment by CammiePone** [comment]
Currently going through them myself as well. So far have figured out it's not Mob Dismemberment

**Comment by LokeYourC3PH** [comment]
For me neither, also not Cyberware, left is Obfuscate (which is a part of MrCrayFish Vehicle Mod and such)

**Comment by CammiePone** [comment]
Interesting, it's none of those 3...

**Comment by LokeYourC3PH** [comment]
Yep, I also came to that conclusion now. Wtf is causing this?

**Comment by CammiePone** [comment]
I have one other idea that I'm trying now. Well, one other mod that it might be. If that's not it, then I do have one idea that will have made all of this pointless had I just tested it before.

**Comment by CammiePone** [comment]
I'm stumped. It's not even Mo' Bends. I thought maybe after you removed it, it didn't update the player render while the effect was still active, and needed to be reapplied, but Mo' Bends works fine.

**Comment by LokeYourC3PH** [comment]
Yup, also tried that but again, no result.

**Comment by LokeYourC3PH** [comment]
I will have to remove the mods in blocks, see which one may cause it, it will take time.

**Comment by CammiePone** [comment]
We'll try and help. Someone suggested a few mods, which I'm testing now. Someone else said Optifine might be it, but I'm doubtful. If you want to try Optifine, go ahead.

**Comment by LokeYourC3PH** [comment]
Well I can hardly imagine why Optifine would do something like that, it works well with other mods that modify character model behavior as far as I know. But sure, I can try.

**Comment by LokeYourC3PH** [comment]
WTF, well, of course it had to be Optifine because why the fuck not.

**Comment by CammiePone** [comment]
Wait, it was Optifine?

**Comment by LokeYourC3PH** [comment]
For whatever reason yeah it was, I will add back all the other mods and test without Optifine.

**Comment by CammiePone** [comment]
Well... that's unfortunate. Thanks, Optifine

**Comment by LokeYourC3PH** [comment]
Well can you not find a fix for it? Usually everyone is able to work around it somehow.

**Comment by CammiePone** [comment]
I'll report it as a bug to Optifine. It's 100% a thing to do with ArtemisLib, so we'll have to work with that.

**Comment by LokeYourC3PH** [comment]
I see, hope you can get it fixed soon :D

**Comment by LokeYourC3PH** [comment]
Ok so, I readded ALL other mods that were suspected, they all work perfectly fine with the resizing mod, so it is ONLY Optifine (not surprised).

**Comment by CammiePone** [comment]
I'm still kinda surprised about that. I know Optifine can be buggy with mods that do things performance wise, but I didn't think it did anything to entity renders.
