### ISSUE TITLE
Forge Server load warning: The mod has no signature.

### ISSUE THREAD

**Issue by Boymann** [CammiePone/Resize-Potion#14]

**Comment by CammiePone** [comment]
Care to provide a log?

**Comment by Boymann** [comment]
[2019-08-02-2.log](https://github.com/CammiePone/Resize-Potion/files/3462266/2019-08-02-2.log)

**Comment by CammiePone** [comment]
Where'd you download the mod from?

**Comment by Boymann** [comment]
Curseforge. I exclusively use curseforge for getting mods.

**Comment by CammiePone** [comment]
Hmm okay, weird. @zabi94 do you think you might know the problem?

**Comment by zabi94** [comment]
Yup, I didn't expect the mod to have signing enabled, so it's probably signing it with my certificate, but expecting your fingerprint since I didn't change it
