### ISSUE TITLE
Incompatbility with Hunger Overhaul

### ISSUE THREAD

**Issue by mxnmnm** [CammiePone/Resize-Potion#15]
When hunger overhaul is installed and a mob has the growth or shrinking potion effect they constantly switch between their modified size and their original size.  I made sure to test it in an instance with just those mods. If you need any other info let me know.

**Comment by mxnmnm** [comment]
I made sure to test it in an instance with just those mods.

**Comment by zabi94** [comment]
Sorry for the long delay.
I need you to check if the problem still exists on the latest version. If it does, does it happen when just the applecore dependency is installed (without hunger overhaul)? Can you provide your `latest.log` file?

**Comment by mxnmnm** [comment]
Well I'll test it when I can but I know it works fine with just the apple-core dependency because I have other mods that still use it and it runs as expected.

**Comment by zabi94** [comment]
Thanks. Because I took a quick look at the code of HO and it doesn't seem to have anything related to entity rendering

**Comment by mxnmnm** [comment]
[latest.log](https://github.com/CammiePone/Resize-Potion/files/4252938/latest.log)
Yep it's still broken with the latest (aka latest that's on curseforge) versions
