### ISSUE TITLE
[Suggestion] Hidden Particle Effects

### ISSUE THREAD

**Issue by mxnmnm** [CammiePone/Resize-Potion#16]
Can there be a config to hide resize's particle effects on mobs?  I mean sure I can turn off particle effects in my animations but I want particle effects in most other situations.  This really becomes annoying when the mob is small and you shrink them.  You end up barely being able to seem them from all of the particles.  Here are some screenshots of what I'm talking about.
![2020-01-23_23 52 25](https://user-images.githubusercontent.com/8508976/73053144-d4a81800-3e3b-11ea-9e50-b545a7034efa.png)
![2020-01-23_23 53 54](https://user-images.githubusercontent.com/8508976/73053147-d540ae80-3e3b-11ea-8701-6612bd51f192.png)

**Comment by CammiePone** [comment]
Set the effect to be ambient with the /effect command.

**Comment by mxnmnm** [comment]
But that requires commands and I want it to be a feature without needing commands and it just being automatically applied.  I mean is there a way to make it so that all resizing effects don't have particles all the time using the command because I don't think there is but if there is a way please let me know.
