### ISSUE TITLE
most recent version does not appear to effect mob sizes

### ISSUE THREAD

**Issue by DragonfallGames** [CammiePone/Resize-Potion#17]
In the most recent version of this mod, mobs take on the effects of the potions, but not the size change.

**Comment by zabi94** [comment]
It seems to work just fine on a bare environment. Can you provide a mod list and your game environment (SP/MP/LAN, it works on some clients and not others, it works for lan host but not lan guests...)?

**Comment by zabi94** [comment]
Any news?

**Comment by DragonfallGames** [comment]
> Any news?

Not sure what you meant by that. Im not trying to use it on a server.

**Comment by zabi94** [comment]
News as in "do you have an answer to the questions?"

**Comment by DragonfallGames** [comment]
> News as in "do you have an answer to the questions?"

Ohhhhh right, where would i find what my game environment is?

**Comment by zabi94** [comment]
Were you playing on a server or in single player? Or maybe it was a single player that was "opened to lan"? If that was the case, were you the one with the game saved locally or were you the one connected to a friend's game?

**Comment by DragonfallGames** [comment]
> Were you playing on a server or in single player? Or maybe it was a single player that was "opened to lan"? If that was the case, were you the one with the game saved locally or were you the one connected to a friend's game?

As I've just stated, i wasn't on a server. Not even the open to plan thing. The game is saved locally. Ive tried it without any mods and it still doesn't work right. Ill give it another go here i guess. 
one thing i just noticed is there isn't any difference if i don't have Artemis Lib  or not. When i took out every other mod i accidentally took out that one but it still did the exact same thing. But you have updated it since I've last tried so let me try the update....
AAAAAnd upon installing your new update (March 1st) it works! Consider this one fixed.
