### ISSUE TITLE
Stuck 1 block tall

### ISSUE THREAD

**Issue by Umbrial** [CammiePone/Resize-Potion#19]
I'm stuck at 1 block tall and clearing effects/drinking milk doesn't reset me. Not wearing the bauble. Potions of growth return me to normal height while they are in effect, but I stay sped up and jumpy

**Comment by zabi94** [comment]
Hello. 
Mod list, mod versions, forge version and the latest.log file (on pastebin) are the bare minimum I need to help you

**Comment by Umbrial** [comment]
I think I found the problem, I updated to the latest version of the mod while the save still had me shrunk. Can't replicate it at all in any other world, I had completely forgotten I'd posted anything. Sorry

**Comment by zabi94** [comment]
Oh, yes, that explains it. I changed an ID in the latest version and it totally makes sense.
If you need me to, I can assist in restoring your normal size if you have access to the save files

**Comment by Umbrial** [comment]
luckily the world it's in is a test world, and this is exactly why I make them

**Comment by zabi94** [comment]
Wise decision
