### ISSUE TITLE
[Request] config option to control what ingredient is used in potion recipe

### ISSUE THREAD

**Issue by xkforce** [CammiePone/Resize-Potion#2]
This can sort of be done with crafttweaker but the problem is that there's a bug in crafttweaker or JEI that does not allow for the original recipe to disappear from JEI after it is replaced.  So if I wanted to change the potion recipes through crafttweaker, I'd end up with both the new and the old recipe showing up in JEI despite the old recipe being removed.  Ideally I would be able to do this through this mod's config so that doesn't happen.  Incidentally, there are duplicates of the current recipe.  i.e. there are three of the same recipe that show up in JEI.

**Comment by CammiePone** [comment]
I'll look into it. If I can figure out how to set the recipe through a config, I'll let you know, and I'll implement it.

**Comment by xkforce** [comment]
Thank you.

**Comment by CammiePone** [comment]
It's wanting to fight me, but it's slowly going somewhere. I'll hopefully have it soon.

**Comment by xkforce** [comment]
Excellent.  Thank you for working on this much appreciated

**Comment by CammiePone** [comment]
Added it in version r1.6! :D
