### ISSUE TITLE
Incompatibility with Liquid Enchanting

### ISSUE THREAD

**Issue by NyanMC** [CammiePone/Resize-Potion#6]
There is an incompatibility with [Liquid Enchanting](https://minecraft.curseforge.com/projects/liquid-enchanting) where if you put any potion from this mod onto an armor using Liquid Enchanting it will create a storm of smoke particles, making the game unplayable.

**Comment by CammiePone** [comment]
The potion effect causes the particles to happen whenever the effect is freshly applied. Meaning Liquid Enchanting constantly refreshes the potion effect. You're going to have to bring it up with them, as there's nothing I can do, other than disable the particles when you have both installed.

**Comment by Phylogeny** [comment]
@CammiePone Please review the PR I submitted a while back (#5), as it does fix this issue.
